export enum ClusterHealthStatus {
  CS_UNKNOWN = 'CS_UNKNOWN',
  CS_HEALTHY = 'CS_HEALTHY',
  CS_UNHEALTHY = 'CS_UNHEALTHY',
  CS_DISCONNECTED = 'CS_DISCONNECTED',
  CS_UPDATING = 'CS_UPDATING',
  CS_CONNECTED = 'CS_CONNECTED',
  CS_UPDATE_FAILED = 'CS_UPDATE_FAILED',
  CS_DEGRADED = 'CS_DEGRADED'
}
