name: Helm deploy
on:
  workflow_dispatch:
     inputs:
        ENV:
            description: 'TAG'
            required: true
            default: ''
            
            
env:
  NS: ${{ vars.NS }}
  ENV: poc
  DOCKER_REG: ${{ vars.DOCKER_REG }}
  PROJECT_ID:  ${{ vars.PROJECT_ID }}
  DOCKER_REPO:  ${{ vars.DOCKER_REPO }}
  APP_NAME:  ${{ vars.APP_NAME }}
  ZK_DOMAIN: ${{ vars.ZK_DOMAIN }}
  TAG: ${{ github.event.inputs.TAG }}
jobs:
  helm-deploy:
    runs-on: self-hosted
    environment: poc
    steps:
      - name: Checkout
        uses: actions/checkout@v3               
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
        

      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: latest
          export_default_credentials: true
      - name: login to docker registry
        run: |
          gcloud auth configure-docker $DOCKER_REG --quiet

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
           cluster_name: '${{ vars.GKE_CLUSTER }}'
           location: '${{ vars.GKE_ZONE }}'
   
      
      - name: Set up helm
        run: |-
           curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
           chmod 700 get_helm.sh
           ./get_helm.sh
      
      - name: Deploy
        run: |-
             helm --install  \
             --set=image.repository=$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$APP_NAME \
             --set=image.tag=$TAG \
             --set ingress.hosts[0].host=dashboard.$ZK_DOMAIN \
             --set ingress.tls.hosts[0]=dashboard.$ZK_DOMAIN \
             upgrade $APP_NAME \
              -f ./helm-charts/$ENV.yaml ./helm-charts/ \
              --create-namespace \
              --namespace $NS 
