name: CICD
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: yarn
        run: yarn build


      - name: docker build
        run: docker build .
